// The `whistleblowerCases` collection: anonymous reports and the follow-up
// messages between reporter and admin (ADR 0005, CLAUDE.md rule 7). Report
// text and messages are stored only encrypted; nothing identifies the reporter.

import type { Types } from "mongoose";

import { mongoose } from "@/lib/db";

import { defineModel, shortText } from "./shared";

const { Schema } = mongoose;

/*
 * PRIVACY RULE: this schema must never get a field that could hold an IP
 * address, user agent, email, name or any other reporter identity, and it has
 * no Mixed field that could smuggle one in. `strict: "throw"` makes an attempt
 * to write an unknown field fail loudly instead of being silently dropped.
 * A test (whistleblower-case.test.ts) checks every path.
 */

export const CASE_STATUSES = ["received", "under_review", "closed"] as const;
export type CaseStatus = (typeof CASE_STATUSES)[number];

export const MESSAGE_AUTHORS = ["reporter", "admin"] as const;
export type MessageAuthor = (typeof MESSAGE_AUTHORS)[number];

/*
 * Upload limits for attachments. Phase 8 (upload route) may adjust the list,
 * but only to types that are never rendered as HTML/script by a browser.
 */
export const WB_ATTACHMENT_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "application/pdf",
] as const;
export const MAX_WB_ATTACHMENT_BYTES = 10 * 1024 * 1024;
export const MAX_WB_ATTACHMENTS = 5;
export const MAX_WB_MESSAGES = 500;
/** Base64 ciphertext limit: roughly 150 KB of text, far above a real report. */
export const MAX_WB_CIPHERTEXT_CHARS = 200_000;

/*
 * Attachment names are generated by the server ("attachment-1.pdf"). The
 * reporter's own file name is never stored: names like "J.Smith_claims.pdf"
 * or "ACCT-LAPTOP-07.jpg" could identify them even though the file itself has
 * its EXIF data removed. The pattern makes the schema reject any other name.
 */
const NEUTRAL_FILE_NAME = /^attachment-\d{1,2}\.(jpg|png|webp|pdf)$/;

/**
 * An AES-256-GCM encrypted value (ADR 0005). The encoding of the three strings
 * is set by src/lib/crypto.ts (Phase 8); `keyVersion` says which key decrypts it.
 */
export interface EncryptedBlob {
  ciphertext: string;
  iv: string;
  tag: string;
  keyVersion: number;
}

/** A file attached to a report, stored in the private R2 bucket. */
export interface CaseAttachment {
  /** Random key (never derived from the file name). */
  storageKey: string;
  /** Neutral server-generated name, e.g. "attachment-1.pdf". */
  fileName: string;
  /** Size in bytes after EXIF stripping. */
  size: number;
  mimeType: string;
}

/** One message in the case thread. */
export interface CaseMessage {
  from: MessageAuthor;
  body: EncryptedBlob;
  createdAt: Date;
}

/** A whistleblower case as stored (and as returned by `lean()`). */
export interface WhistleblowerCase {
  _id: Types.ObjectId;
  /** Shown once to the reporter, who uses it with the password to sign in. */
  caseNumber: string;
  /**
   * Hash of the case password. Optional in this type because queries leave it
   * out (`select: false`); the one login query must use `.select("+passwordHash")`.
   */
  passwordHash?: string;
  relationship?: string;
  concernType?: string;
  /** The report text, encrypted. */
  body: EncryptedBlob;
  attachments: CaseAttachment[];
  status: CaseStatus;
  messages: CaseMessage[];
  createdAt: Date;
  updatedAt: Date;
}

const encryptedBlobSchema = new Schema<EncryptedBlob>(
  {
    ciphertext: {
      type: String,
      required: true,
      maxlength: MAX_WB_CIPHERTEXT_CHARS,
    },
    iv: { type: String, required: true, maxlength: 64 },
    tag: { type: String, required: true, maxlength: 64 },
    keyVersion: {
      type: Number,
      required: true,
      min: 1,
      validate: {
        validator: Number.isInteger,
        message: "keyVersion must be a whole number",
      },
    },
  },
  { _id: false, strict: "throw" },
);

const attachmentSchema = new Schema<CaseAttachment>(
  {
    storageKey: { type: String, required: true, trim: true, maxlength: 512 },
    fileName: {
      type: String,
      required: true,
      match: [NEUTRAL_FILE_NAME, "fileName must be server-generated"],
    },
    size: {
      type: Number,
      required: true,
      min: 1,
      max: MAX_WB_ATTACHMENT_BYTES,
      validate: {
        validator: Number.isInteger,
        message: "size must be whole bytes",
      },
    },
    mimeType: { type: String, required: true, enum: WB_ATTACHMENT_MIME_TYPES },
  },
  { _id: false, strict: "throw" },
);

const messageSchema = new Schema<CaseMessage>(
  {
    from: { type: String, required: true, enum: MESSAGE_AUTHORS },
    body: { type: encryptedBlobSchema, required: true },
    createdAt: { type: Date, required: true, default: Date.now },
  },
  { _id: false, strict: "throw" },
);

const whistleblowerCaseSchema = new Schema<WhistleblowerCase>(
  {
    caseNumber: { type: String, required: true, trim: true, maxlength: 32 },
    // Excluded from every query by default, so a case listing never loads it.
    passwordHash: { type: String, required: true, select: false },
    // Categories the reporter picks from fixed lists (lists set in Phase 8).
    relationship: shortText,
    concernType: shortText,
    body: { type: encryptedBlobSchema, required: true },
    attachments: {
      type: [attachmentSchema],
      default: [],
      validate: {
        validator: (list: unknown[]) => list.length <= MAX_WB_ATTACHMENTS,
        message: `at most ${MAX_WB_ATTACHMENTS} attachments`,
      },
    },
    status: {
      type: String,
      required: true,
      enum: CASE_STATUSES,
      default: "received",
    },
    // Capped so one case can never approach MongoDB's 16 MB document limit.
    // Array validators don't run on `$push`: Phase 8 must append with a
    // length guard in the update filter ({ "messages.499": { $exists: false } }).
    messages: {
      type: [messageSchema],
      default: [],
      validate: {
        validator: (list: unknown[]) => list.length <= MAX_WB_MESSAGES,
        message: `at most ${MAX_WB_MESSAGES} messages`,
      },
    },
  },
  { collection: "whistleblowerCases", timestamps: true, strict: "throw" },
);

// The reporter signs in with the case number.
whistleblowerCaseSchema.index({ caseNumber: 1 }, { unique: true });

export const WhistleblowerCaseModel = defineModel<WhistleblowerCase>(
  "WhistleblowerCase",
  whistleblowerCaseSchema,
);
