// shadcn/ui component (radix-nova), generated by the shadcn CLI; animation, dark-mode and blur classes were stripped (ADR 0034).
import { cn } from "@/lib/utils";

function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      className={cn("rounded-md bg-muted", className)}
      {...props}
    />
  );
}

export { Skeleton };
